# Generated by Django 5.2.6 on 2025-11-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_admin_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.URLField(default='https://cdn.mmem.com.au/media/catalog/product/placeholder/default/product-image.jpg', help_text='Product image URL', max_length=500),
        ),
    ]
