# Generated by Django 5.2.6 on 2025-11-04 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_remove_category_parent_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_subcategory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, help_text='Leave blank for main categories, select a parent for subcategories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='admin_panel.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Can be assigned to either main category or subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='admin_panel.category'),
        ),
    ]
