# Generated by Django 5.2.7 on 2025-11-04 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_remove_category_is_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Select a subcategory if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_products', to='admin_panel.category'),
        ),
    ]
