# Generated by Django 5.2.6 on 2025-11-12 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_order_customer_email_alter_category_parent_category_and_more'),
        ('customer_website', '0011_alter_customer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Coupon code used (for display purposes)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('coupon_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(help_text='Unique coupon code', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the coupon')),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount amount (fixed) or percentage (0-100)', max_digits=10)),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum order value to apply coupon', max_digits=10)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount for percentage coupons', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(help_text='Coupon valid from date')),
                ('valid_until', models.DateTimeField(help_text='Coupon valid until date')),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='Total number of times coupon can be used (0 = unlimited)')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Current usage count')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, help_text='Categories this coupon applies to (leave empty for all)', related_name='coupons', to='admin_panel.category')),
                ('applicable_products', models.ManyToManyField(blank=True, help_text='Products this coupon applies to (leave empty for all)', related_name='coupons', to='admin_panel.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='admin_panel.coupon'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('coupon_usage_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='admin_panel.coupon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='customer_website.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='admin_panel.order')),
            ],
            options={
                'unique_together': {('coupon', 'customer', 'order')},
            },
        ),
    ]
