# Generated by Django 5.2.6 on 2025-11-12 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_order_coupon_code_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_value',
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateField(help_text='Coupon valid from date (midnight)'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateField(help_text='Coupon valid until date (midnight)'),
        ),
    ]
