# Generated by Django 5.2.6 on 2025-11-12 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_remove_coupon_discount_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_products',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, help_text='Main categories this coupon applies to (leave empty for all)', limit_choices_to={'parent_category__isnull': True}, related_name='coupons', to='admin_panel.category'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
