# Generated by Django 5.2.6 on 2025-11-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_remove_coupon_applicable_products_and_more'),
        ('customer_website', '0011_alter_customer_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='assigned_customers',
            field=models.ManyToManyField(blank=True, help_text='Specific customers this coupon is assigned to (leave empty for all customers)', related_name='assigned_coupons', to='customer_website.customer'),
        ),
    ]
