# Generated by Django 5.2.6 on 2025-10-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('education', models.CharField(blank=True, max_length=100, null=True)),
                ('household_size', models.PositiveIntegerField(blank=True, null=True)),
                ('has_children', models.BooleanField(default=False)),
                ('monthly_income_sgd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preferred_category', models.CharField(blank=True, default='General', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
