# Generated by Django 5.2.6 on 2025-10-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
