# Generated by Django 5.2.6 on 2025-10-26 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_website', '0002_alter_customer_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
