# Generated by Django 5.2.6 on 2025-11-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_website', '0003_customer_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.URLField(default='https://www.pngmart.com/files/21/Admin-Profile-Vector-PNG-Clipart.png', help_text='Profile picture URL', max_length=500),
        ),
    ]
