# Generated by Django 5.2.6 on 2025-11-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_website', '0004_customer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='education',
            field=models.CharField(blank=True, choices=[('High School', 'High School'), ('Diploma', 'Diploma'), ('Bachelor', "Bachelor's Degree"), ('Master', "Master's Degree"), ('PhD', 'PhD')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Retired', 'Retired'), ('Self-employed', 'Self-employed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Unspecified', 'Prefer not to say')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='has_children',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Freelancer', 'Freelancer'), ('Unemployed', 'Unemployed'), ('Student', 'Student'), ('Retired', 'Retired')], max_length=100, null=True),
        ),
    ]
