# Generated by Django 5.2.6 on 2025-11-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_website', '0005_alter_customer_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='noreply@auroramart.com', help_text='Customer email address', max_length=254),
        ),
    ]
