# Generated by Django 5.2.7 on 2025-11-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_website', '0006_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='default@gmail.com', help_text='Customer email address', max_length=254),
        ),
    ]
