# Generated by Django 5.2.6 on 2025-11-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_website', '0007_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
