# Generated by Django 5.2.6 on 2025-11-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_website', '0008_remove_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='has_children',
        ),
        migrations.AddField(
            model_name='customer',
            name='number_of_children',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
