# Generated by Django 5.2.6 on 2025-11-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_website', '0009_remove_customer_has_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='education',
            field=models.CharField(blank=True, choices=[('Secondary', 'Secondary'), ('Diploma', 'Diploma'), ('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Self-employed', 'Self-employed'), ('Student', 'Student'), ('Retired', 'Retired')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, choices=[('Admin', 'Administrative'), ('Education', 'Education'), ('Sales', 'Sales'), ('Service', 'Service Industry'), ('Skilled Trades', 'Skilled Trades'), ('Tech', 'Technology')], max_length=100, null=True),
        ),
    ]
