# Generated by Django 5.2.7 on 2025-11-14 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_coupon_assigned_customers'),
        ('customer_website', '0011_alter_customer_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlist_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='customer_website.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='admin_panel.product')),
            ],
            options={
                'ordering': ['-added_date'],
                'unique_together': {('customer', 'product')},
            },
        ),
    ]
