# Generated by Django 5.2.6 on 2025-10-21 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuroraMart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_id',
        ),
    ]
