# Generated by Django 5.2.6 on 2025-10-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuroraMart', '0002_rename_order_orderitem_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='parent_category',
        ),
    ]
